from fpdf import FPDF
from datetime import datetime
import os
import re


def clean_text(text: str) -> str:
    if text is None:
        return ""
    text = str(text)
    text = text.replace("✅", "").replace("❌", "")
    text = text.replace("🔺", "").replace("🔻", "")
    text = text.replace("—", "-").replace("–", "-")
    text = text.encode("ascii", "ignore").decode()
    text = re.sub(r"\s+", " ", text).strip()
    return text


def safe_multicell(pdf, w, h, txt):
    txt = clean_text(txt)
    if txt == "":
        return
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(w, h, txt)


def add_image_if_exists(pdf, image_path, x=None, w=170):
    """
    Adds image to PDF only if file exists
    """
    if image_path and os.path.exists(image_path):
        pdf.ln(3)
        pdf.set_x(pdf.l_margin)
        pdf.image(image_path, x=x if x else pdf.l_margin, w=w)
        pdf.ln(5)


def generate_pdf_report(
    patient_details: dict,
    final_prediction: str,
    confidence: float,
    risk_score: float,
    risk_category: str,
    top_positive: list,
    top_negative: list,
    recommendations: list,
    save_path="reports/heart_disease_report.pdf",
    shap_summary_img=None,
    shap_bar_img=None,
    shap_local_img=None,
    risk_meter_img=None
):
    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    usable_width = 190

    # Title
    pdf.set_font("Arial", "B", 16)
    safe_multicell(pdf, usable_width, 10, "Heart Disease Prediction Report")

    pdf.set_font("Arial", "", 11)
    safe_multicell(pdf, usable_width, 7, f"Generated on: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}")

    pdf.ln(2)

    # Patient details
    pdf.set_font("Arial", "B", 13)
    safe_multicell(pdf, usable_width, 8, "Patient Details")

    pdf.set_font("Arial", "", 11)
    for k, v in patient_details.items():
        safe_multicell(pdf, usable_width, 7, f"{k}: {v}")

    pdf.ln(2)

    # Prediction
    pdf.set_font("Arial", "B", 13)
    safe_multicell(pdf, usable_width, 8, "Prediction Results")

    pdf.set_font("Arial", "", 11)
    safe_multicell(pdf, usable_width, 7, f"Final Prediction: {final_prediction}")
    safe_multicell(pdf, usable_width, 7, f"Ensemble Confidence: {confidence:.2f}%")
    safe_multicell(pdf, usable_width, 7, f"Risk Score: {risk_score:.2f} / 100")
    safe_multicell(pdf, usable_width, 7, f"Risk Category: {risk_category}")

    # ✅ Risk Meter Image
    pdf.set_font("Arial", "B", 13)
    safe_multicell(pdf, usable_width, 8, "Risk Meter")
    add_image_if_exists(pdf, risk_meter_img, w=170)

    # ✅ SHAP Images
    pdf.set_font("Arial", "B", 13)
    safe_multicell(pdf, usable_width, 8, "Explainable AI (SHAP)")

    pdf.set_font("Arial", "", 11)
    safe_multicell(pdf, usable_width, 7, "Global SHAP Summary Plot:")
    add_image_if_exists(pdf, shap_summary_img, w=170)

    safe_multicell(pdf, usable_width, 7, "Global SHAP Feature Importance:")
    add_image_if_exists(pdf, shap_bar_img, w=170)

    safe_multicell(pdf, usable_width, 7, "Local SHAP Waterfall (Current Patient):")
    add_image_if_exists(pdf, shap_local_img, w=170)

    # SHAP text summary
    pdf.set_font("Arial", "", 11)
    safe_multicell(pdf, usable_width, 7, "Top Features Increasing Risk:")
    for feat in top_positive:
        safe_multicell(pdf, usable_width, 6, f"- {feat}")

    pdf.ln(1)
    safe_multicell(pdf, usable_width, 7, "Top Features Decreasing Risk:")
    for feat in top_negative:
        safe_multicell(pdf, usable_width, 6, f"- {feat}")

    pdf.ln(2)

    # Recommendations
    pdf.set_font("Arial", "B", 13)
    safe_multicell(pdf, usable_width, 8, "Personalized Recommendations")

    pdf.set_font("Arial", "", 11)
    for i, r in enumerate(recommendations, 1):
        safe_multicell(pdf, usable_width, 6, f"{i}. {r}")

    pdf.ln(2)

    # Footer
    pdf.set_font("Arial", "I", 10)
    safe_multicell(pdf, usable_width, 6,
                   "Note: This report is generated by an AI model and should not be treated as final medical advice. "
                   "Please consult a certified doctor for diagnosis.")

    pdf.output(save_path)
    return save_path
